In [2]:
my_list = [1,2,3]

import numpy as np

np.array(my_list) # use the numpy module, array() function to cast the list into an array

array([1, 2, 3])

In [50]:
arr0=np.arange(25)
arr0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
np.sqrt(arr0)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [4]:
np.arange(0,10,2) # here 2 in the step, different from linespace

array([0, 2, 4, 6, 8])

In [5]:
np.zeros(3) # similar to np.ones(4)

array([0., 0., 0.])

In [6]:
np.zeros((2,5)) # inside is a tuple

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.linspace(0,100, 11) # 11 = 10 intervals and 11 endpoints

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [11]:
np.random.rand(5) # rand function returns a random number between 0 and 1

array([0.2990995 , 0.66740742, 0.37108302, 0.66213608, 0.32173542])

In [12]:
np.random.rand(3,4) # inside is not a tuple, different from zeros functions.

array([[0.89847018, 0.77815199, 0.20685015, 0.2639115 ],
       [0.07867978, 0.57328834, 0.52823546, 0.38349747],
       [0.0162717 , 0.47146785, 0.44671066, 0.0675691 ]])

In [13]:
np.random.randn(3,4) # here randn function return a random number near 0;

array([[ 0.56798362, -0.9507247 , -0.58910558, -1.48826742],
       [ 0.0980138 ,  0.42994942, -0.81705709, -1.67957568],
       [-1.20824099, -1.00002406, -0.56525538, -0.42339986]])

In [14]:
np.random.randint(1,100,10) # 10 random integer between 1 and 100;

array([82, 28, 89,  1, 84, 26,  1, 76, 11, 61])

In [27]:
ranarr1=np.random.randint(0,50,20)
ranarr1

array([33, 20,  0, 12, 29, 35, 41, 17, 23, 10, 46,  9,  7, 34, 30, 45, 27,
       31, 46,  7])

In [42]:
arr_boolean_25=ranarr1<25
arr_boolean_25

array([False, False, False,  True, False, False, False,  True,  True,
        True, False,  True,  True, False, False, False, False, False,
       False,  True])

In [48]:
ranarr1[arr_boolean_25]


array([12, 17, 23, 10,  9,  7,  7])

In [28]:
ranarr1[0:3]= 50
ranarr1

array([50, 50, 50, 12, 29, 35, 41, 17, 23, 10, 46,  9,  7, 34, 30, 45, 27,
       31, 46,  7])

In [29]:
ranarr2 = ranarr1.reshape(4,5)
ranarr2

array([[50, 50, 50, 12, 29],
       [35, 41, 17, 23, 10],
       [46,  9,  7, 34, 30],
       [45, 27, 31, 46,  7]])

In [33]:
arr_slice = ranarr2[:2,1:]
arr_slice

array([[50, 50, 12, 29],
       [41, 17, 23, 10]])

In [40]:
arr_boolean = ranarr2 >25
arr_boolean

array([[ True,  True,  True, False,  True],
       [ True,  True, False, False, False],
       [ True, False, False,  True,  True],
       [ True,  True,  True,  True, False]])

In [34]:
ranarr1.max()

50

In [35]:
ranarr1.min()

7

In [36]:
ranarr1.argmax() # returns the index the max number

0

In [37]:
ranarr2.shape # returns the index the max number

(4, 5)

In [38]:
ranarr1.shape

(20,)